# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    TIMEZONE: '%env(APP_TIMEZONE)%'
    MESSAGEBIRD_KEY: '%env(MESSAGEBIRD_KEY)%'
    APP_PHONE: '%env(APP_PHONE)%'
    APP_EMAIL: '%env(APP_EMAIL)%'
    MICROSOFT_CLIENT_ID: '%env(MICROSOFT_CLIENT_ID)%'
    MICROSOFT_TENANT_ID: '%env(MICROSOFT_TENANT_ID)%'
    MICROSOFT_CLIENT_SECRET: '%env(MICROSOFT_CLIENT_SECRET)%'
    APP_URL: '%env(APP_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\PermissionAnnotationListener:
        class: App\EventListener\PermissionAnnotationListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    App\EventListener\AdminAnnotationListener:
        class: App\EventListener\PermissionAnnotationListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    App\EventListener\NotificationListener:
        class: App\EventListener\NotificationListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    App\EventListener\LocaleListener:
        class: App\EventListener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

