version: '3.3'
services:
  nginx-proxy:
    container_name: tfg_proxy
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - ./certs:/etc/nginx/certs
        - ./services/nginx-proxy/configuration.conf:/etc/nginx/conf.d/configuration.conf
    networks:
        - tfg-backend
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    container_name: tfg_letsencrypt
    image: nginxproxy/acme-companion
    restart: always
    environment:
        - DEFAULT_EMAIL=i92cajaa@uco.es
    volumes_from:
        - nginx-proxy
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - acme:/etc/acme.sh
    depends_on:
        - nginx-proxy
  backend:
    container_name: tfg_backend
    restart: always
    build:
      context: ./services/php/symfony6
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./../backend:/var/www/html
    networks:
      - tfg-backend
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=localhost
      - LETSENCRYPT_EMAIL=i92cajaa@uco.es

  mysql:
    container_name: tfg_mysql
    restart: always
    image: mysql:8
    env_file: ./.env
    command:
      - --max_allowed_packet=500M
      - --sql-mode=
      - --innodb-buffer-pool-size=5G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=2G
      - --innodb_flush_method=O_DIRECT
    volumes:
      - tfg-mysql:/var/lib/mysql
      - ./sql:/root/
    networks:
      - tfg-backend

  phpmyadmin:
    container_name: tfg_phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
    - "8084:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
    networks:
      - tfg-backend


networks:
  tfg-backend:
    driver: bridge

volumes:
  tfg-mysql:
    driver: local
  vhost:
      driver: local
  html:
      driver: local
  acme:
      driver: local
